name: poke_api
description: Poke API.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_riverpod: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon_launcher/
    - assets/images/
    - lib/.env

flutter_launcher_icons:
  android: "launcher_icon"
  # ios: true
  image_path_android: "assets/icon_launcher/pokeapi_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon_launcher/pokeapi_logo.png"
